type User{
    id:Int!
    name:String!
    email:String!
}
type Comment{
    id:Int!
    content:String!
    date:String!
    author:User!
}

type Post{
    id:Int!
    userID:Int!
    title:String!
    body:String!
    comments:[Comment]!
}

# Query

type Query{
    posts:[Post]!
    post(id:Int!):Post!
}

query{
    post(id:1){
        id
        title
    }
}

query{
    posts{
        id
        title
    }
}

# Mutations
type Message{
    message:String!
}

type mutation{
    addPost(userId:Int!,title:String!,body:String!):Post
    updatePost(id:Int!,title:String!,body:String!):Post
    deletePost(id:Int!):Message
}

mutation{
    addPost(userId:1,title:"Learning GraphQL",body:"Hello world"){
        id
        title
        comments
    }
}
# Subscription